### PR TITLE
Issues #19: Player Count Filters

### PR DESCRIPTION
**Pull request by ArthurMousatov**
As per Issue #19, this PR adds 3 new filters: Filtering Full Servers, Filtering Max Players, Filtering Min Players. 

image

There is, however, a small issue with the NumericUpDown AvaloniaUI element: it does not allow null-able values (yet? see: https://github.com/AvaloniaUI/Avalonia/discussions/8113). Because of this, once the player count max value is set, there is no way to reset it, For now, I see 3 solutions:
* Check and see if an updated AvaloniaUI has the nullable Numeric Value
* Set a sensible default for max/min to specify we don't want to use these filters (-1?)
* Use a default Text Input Box instead of a NumericUpDown box

Open to Input!

### CODE REVIEW

**Comment by PJB3005** [comment]
For the count filters thing, I think maybe the best solution would be a separate check box that enables the number field?

**Comment by ArthurMousatov** [comment]
> For the count filters thing, I think maybe the best solution would be a separate check box that enables the number field?

Sure, I pushed some changes.

image

**Comment by PJB3005** [comment]
Sorry for taking so long to get to this. I'll just quickly clean it up and merge it.

**Comment by PJB3005** [comment]
Done in that commit.

**Pull request closed without merging**
