### PR TITLE
Upgrade to Avalonia 11

### PR DESCRIPTION
**Pull request by Visne**
Incorporates #93.

Fixes drag and drop and account switcher. I couldn't find any other bugs. ~Upgrading to 11.0.5 appears to completely nuke source generators for me, but I'm not sure if that's just an issue on my end. (Edit: GitHub build script/test can't seem to handle it either. shrug)~

### CODE REVIEW

**Comment by PJB3005** [comment]
I know there were some minor stylistic changes to some controls like the tab bar. Are they a significant issue?

**Comment by Visne** [comment]
Yes actually, selected tab has a bit of a wacky color:
image
I'll see if I can fix that, but I didn't notice any other style changes.

**Comment by Visne** [comment]
image
The rot consumes

**Comment by Visne** [comment]
Should be good to go now

**Pull request merged**
