### PR TITLE
Server suggestions

### PR DESCRIPTION
**Pull request by 20kdc**
I'm not that great with Avalonia's reactive UI stuff, so I fully expect this to need some code review before it'll be accepted.

If the user has <= 4 favorites, assumes that they might be interested in more servers, and therefore shows them suggestions from the main server list.

This is an attempt to implement the Rane proposal for the Everybody's Gone To The Lizard problem.

image

### CODE REVIEW

**Comment by Elijahrane** [comment]
2 small bits of feedback:
1. I might set the upper limit at 3 instead of 4, you don't want to make the home screen too bloated/noisy.
2. This whole section should line up with the bottom instead of wasting that empty space 
image
I think you want to maximize the distance between the favorites part and the suggestions part

**Comment by 20kdc** [comment]
image
the requested screenshot

**Comment by 20kdc** [comment]
image
Resizing working as requested as of 3d3382c

**Comment by Elijahrane** [comment]
> image the requested screenshot

So it introduces a scrollbar, probably worth reducing to 3 then

**Comment by 20kdc** [comment]
Alright, resulting worst-case situation as of 6d4d733 :
image

**Comment by Elijahrane** [comment]
Looks perfect now I think

**Pull request merged**
