### PR TITLE
update nix to 23.11

### PR DESCRIPTION
**Pull request by lizelive**

### CODE REVIEW

**Comment by PJB3005** [comment]
cc @Zumorica ?

**Comment by lizelive** [comment]
this goes with https://github.com/space-wizards/SS14.Launcher/pull/117 as well

**Review by Zumorica — APPROVED** [review]
Haven't tested, but doesn't look like it'd break anything.

**Comment by Zumorica** [comment]
Actually tested this now and it does in fact break it-- 
@lizelive Just pull the changes in #117 into this PR, no need to keep them separate.

**Comment by lizelive** [comment]
@Zumorica did requested changes but please note master is currently broken (fixed in #117 ) hence why i split into two prs

**Pull request merged**
