### PR TITLE
Change minimum windows version to windows 10 version 1607

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
Why version 1607? Cause i have no fucking clue what to set it to!

Windows build versions here

https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
Maybe Windows 10 version 2004 is a better choice

**Comment by Visne** [comment]
Why?

**Comment by deathride58** [comment]
The absolute minimum requirement for dotnet 8 is Windows 10 1607 (Anniversary update, released back in 2016), for reference

**Comment by VasilisThePikachu** [comment]
> Why?

Windows 8.1 is unsupported. Unsupported by [Steam as of recently](https://help.steampowered.com/en/faqs/view/4784-4F2B-1321-800A) and not supported for dotnet 8 as Bhijn said.

It should not be up to us to support unsupported windows versions

**Comment by Visne** [comment]
As far as I know the warning message appears on every startup, and this makes sense for Windows 7 as it is practically impossible to play SS14 on it without some serious tweaking, but as this is not the case for Windows 8 (as far as I know) it seems quite annoying to show the warning every time when someone might still be able to play the game just fine.

**Comment by VasilisThePikachu** [comment]
> As far as I know the warning message appears on every startup, and this makes sense for Windows 7 as it is practically impossible to play SS14 on it without some serious tweaking, but as this is not the case for Windows 8 (as far as I know) it seems quite annoying to show the warning every time when someone might still be able to play the game just fine.

Once again

dotnet 8 does not support 8.1

**Comment by Visne** [comment]
I figured that was "not supported" in the same sense as "Microsoft is not supporting Windows 7", i.e. "it just works but no one is going to help you if it breaks". If .NET 8 completely breaks SS14 on Windows 8 then it's fine to me.

**Comment by deathride58** [comment]
Is there anyone on Windows 7 able to run SS14 at all? Support for both 7 and 8.1 were dropped simultaneously with the release of Dotnet 7, and we imagine things are probably more unstable on 7 and 8.1 with Dotnet 8

**Comment by Visne** [comment]
I think that if you update the root certificates you can play on Windows 7 just fine, but I'm not sure if anyone is doing it.

**Comment by VasilisThePikachu** [comment]
Honestly if you are going to the point where you have to update stuff like root certs in order to play your funny space game you may as well update to windows 10/11 or go to linux

**Comment by Visne** [comment]
I know, but I don't think that's an issue on Windows 8.

**Pull request merged**
