### PR TITLE
Show launcher version in the main window

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
Now comes with coding warcrimes (in my opinion)

(and tiny ass minor code style fix)

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
FUCK I DID MASTER

**Comment by VasilisThePikachu** [comment]
You never saw anything

**Comment by Simyon264** [comment]
> You never saw anything

But I did...

**Comment by Errant-4** [comment]
This is why you don't code at 00:32

**Pull request closed without merging**
